name: Build MoeMemos APK
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
      - name: Clean build cache
        run: ./gradlew cleanBuildCache        
      - name: Clean Gradle cache
        run: ./gradlew clean
      - name: Build Release APK
        run: ./gradlew assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: moe-memos-release.apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk
